In [2]:
import numpy as np, pandas as pd, matplotlib as mpl
%matplotlib inline
mpl.rcParams["figure.facecolor"] = "white"
from matplotlib import pyplot as plt


In [ ]:
x = pd.read_hdf("rst0.h5", "train")
y = pd.read_csv('DS_2_train.csv', index_col=0)
z = pd.merge(y, x, left_index=True, right_index=True)


/fefs/disk/usr100/gentoo/usr/lib64/python3.6/site-packages/numpy/lib/arraysetops.py:463: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [9]:
def addf(df):
    df['eX'] = np.arctan2(1, df.TX)
    df['rX'] = df.Z*np.cos(df.eX) + df.X*np.sin(df.eX)
    df['eY'] = np.arctan2(1, df.TY)
    df['rY'] = df.Z*np.cos(df.eY) + df.Y*np.sin(df.eY)

addf(z)

In [22]:
tx2 = z.TX ** 2
ty2 = z.TY ** 2
tz2 = 1/(1 + tx2 + ty2)
bx2 = tx2 * tz2
by2 = ty2 * tz2
bxy = np.sqrt(bx2 * by2)
bz1 = np.sqrt(tz2) + 1

z['bX'] = (1-bx2/bz1) * z.X - bxy/bz1 * z.Y - z.TX * z.Z
z['bY'] = - bxy/bz1 * z.X + (1-by2/bz1) * z.Y - z.TX * z.Z

In [84]:
bn = 77
zb = z.query("rst0 < 0.5 & signal > 0.5")
zb1 = zb.query("brick_number=={}".format(bn))

In [85]:
za = z.query("signal > 0.5")
za1 = za.query("brick_number=={}".format(bn))


In [86]:
plt.plot(za1.bX, za1.bY, '.', alpha=0.2)
plt.plot(zb1.bX, zb1.bY, 'o')

In [87]:
plt.plot(za1.X, za1.Y, '.', alpha=0.5)
plt.plot(zb1.X, zb1.Y, 'o')


In [88]:
z1 = z.query('brick_number=={}'.format(bn))

In [89]:
c, e1, e2, e3 = plt.hist2d(z1.bX, z1.bY, weights=z1.rst0.values, bins=50)
plt.plot(zb1.bX, zb1.bY, 'x', color="red")
plt.show()
plt.plot(z1.bX, z1.bY, '.', alpha=0.1)
plt.plot(zb1.bX, zb1.bY, 'x', color="red")
plt.show()



In [92]:
c, e1, e2, e3 = plt.hist2d(z1.Z, z1.Y, weights=z1.rst0.values, bins=50)
plt.plot(zb1.Z, zb1.Y, 'x', color="red")
plt.show()
plt.plot(z1.Z, z1.Y, '.', alpha=0.1)
plt.plot(zb1.Z, zb1.Y, 'x', color="red")
plt.show()



In [32]:
z1.rst0.valueso

array([  2.03238727e-04,   6.31047937e-04,   6.70780521e-03, ...,
         2.05194442e-06,   1.77215524e-02,   1.75040492e-04], dtype=float32)

In [19]:
plt.hist(np.sqrt(z.TX ** 2 + z.TY ** 2))

(array([  5.49806000e+05,   1.45793600e+06,   2.49809500e+06,
          3.02172400e+06,   1.95753300e+06,   3.12540000e+05,
          6.15300000e+03,   1.89100000e+03,   5.94000000e+02,
          1.14000000e+02]),
 array([  1.26501774e-04,   1.34783663e-01,   2.69440824e-01,
          4.04097985e-01,   5.38755146e-01,   6.73412307e-01,
          8.08069468e-01,   9.42726629e-01,   1.07738379e+00,
          1.21204095e+00,   1.34669811e+00]),
 <a list of 10 Patch objects>)

In [20]:
z.query("TX**2 + TY**2 > 1")

         event_id             X             Y        Z        TX        TY  \
index                                                                        
9631        13102  47520.363281  25755.378906  69822.0 -0.810891  0.648075   
16410       19427  40259.339844  36536.140625  62064.0 -0.736207 -0.764379   
31102         195  51781.238281  21831.496094  53013.0  0.768452  0.711003   
32883       23165  41594.578125  38970.515625  58185.0 -0.944740 -0.331315   
45215       34765  57687.667969  22267.976562  49134.0 -0.834082 -0.749237   
46178        3734  60609.691406  33944.347656  37497.0  0.761198  0.675270   
48025       10457  47202.039062  46950.007812  46548.0  0.374130  0.997696   
58102       37502  41637.304688  15404.992188  62064.0  0.498261  0.959052   
65078        8931  51145.382812  19797.472656  63357.0  0.916393  0.468397   
93795        6822  50553.515625  38716.007812  45255.0 -0.593406  0.833993   
97239       24497  60620.695312  52586.566406  64650.0  0.292085

In [21]:
np.sqrt(0.5)

0.70710678118654757